version: "3"

volumes:
  pgadmin-data:

services:
  app:
    container_name: java-app
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
      args:
        VARIANT: 11
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "false"
        NODE_VERSION: "none"
        USER_UID: 1000
        USER_GID: 1000
    env_file: env/app.env
    volumes:
      - "/home/guilherme/Documents/projects/git/personal/semana-spring-react.git:/workspace:cached"
    network_mode: service:dbDev
    command: sleep infinity
    depends_on:
      - dbDev

  dbDev:
    container_name: psql-dev
    image: "guilhermercarvalho/semanaspringreact-bd_psql14"
    build:
      context: .
      dockerfile: dockerfiles/dbDev.Dockerfile
    env_file: env/db.dev.env
    restart: unless-stopped

  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4
    env_file: env/pgadmin.env
    ports:
      - 8081:80
    depends_on:
      - dbDev
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
    restart: unless-stopped
