version: '3.8'

services:
  app:
    image: "guilhermercarvalho/dsvendas-app-java:v1.0.dev"
    container_name: dsvendas-app-java
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
    env_file:
      - env/app.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    container_name: dsvendas-db-postgres
    image: postgres:14-alpine3.14
    restart: unless-stopped
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dvendas.sql:ro
    env_file: env/db.env
